os: linux
matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      language: generic
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: "3.6"
script: true
install: true
